### ISSUE TITLE
Problem with Netmarble's Games (Seven Knights, EvilBane, etc)

### ISSUE THREAD

**Issue by What-Zit-Tooya** [SudoCode755/SudoHide#1]
Link to Play Store : https://play.google.com/store/apps/details?id=com.netmarble.sknightsgb
Downloaded and install it. After i launch it, it show me a pop up "Security Alert (code : 2) [xposed]" then it closes automatically.
After that, i hide Xposed from Seven Knight using SudoHide, then reboot phone. But it does not work, Seven Knight still detect xposed in my device.
I'm using Redmi Note 3 Pro (Snapdragon variants) with MIUI 7 ROM.
Hope you add support to that game / other games like that, almost all games developed by Netmarble Games have that issue.
Here for dev id Netmarble Games https://play.google.com/store/apps/dev?id=5258410538530331508
Thanks in advance. :)

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
It might be using SecurityNet to check for Xposed, try installing "No Device Check", however, this may not work as well due to some developments, people are trying to fix it...

**Comment by What-Zit-Tooya** [comment]
@L-a-n-g-o-l-i-e-r-s recently tried it, but still no luck.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I'll bet that either the problem is more specific or that it's using SafetyNet's online functions or something. I haven't any clues. No experience in coding, just my thoughts.

**Comment by NHellFire** [comment]
It uses SafetyNet and has a native library that apparently also does some checking. I guess it's the native library reporting xposed, since as far as I know, SafetyNet doesn't specify a failure reason.

**Comment by What-Zit-Tooya** [comment]
@L-a-n-g-o-l-i-e-r-s Ok, no problem

@NHellFire Could it be bypassed?

**Comment by poutros** [comment]
@exodius48 https://github.com/devadvance/rootcloak/wiki/Working-and-Nonworking-Apps
Check under "Apps with calls most likely can never be directly intercepted by Xposed". If these apps are using the native library then they probably won't work.

**Comment by What-Zit-Tooya** [comment]
@poutros All netmarble games's not available there

**Comment by poutros** [comment]
@exodius48 I know, but look at the reason why those other apps are there. If the apps you mention use the native library to find things then it is likely that they won't work.

**Comment by What-Zit-Tooya** [comment]
@poutros I don't know it uses native library or not, i don't know how to check

**Comment by NHellFire** [comment]
Root cloak beta has support for native calls and from my own testing it works correctly.
It probably needs some more calls added though, but unfortunately netmarble don't support x86 so I can't try it in the emulator.

**Comment by poutros** [comment]
@NHellFire Yeah, I went to the wiki again and saw the 3.0 beta page but it seems to not be xposed based?

**Comment by NHellFire** [comment]
Still is xposed for java calls. But native calls can't be handled by
xposed, so we added our own library to do it

**Comment by ErN35T** [comment]
If U guys still having problem with 7K, try using automate, 7K detects xposed folders. While using automate we toggle renaming xposed folder for used with Netmarble games

**Comment by What-Zit-Tooya** [comment]
@ErN35T how to do it? any tutorial?

**Comment by ErN35T** [comment]
Download automate, go to community, search in games, Netmarble - xposed toggle

**Comment by vexelx** [comment]
I am having a problem with seven knights...some error screen pops up
( Error openning file : res/ux/ui_text_pop-up.txt )
( error: ux/ui_text_value.txt. file not found )
