### ISSUE TITLE
App crash in Android 7.1.2

### ISSUE THREAD

**Issue by ghost** [SudoCode755/SudoHide#4]
10-22 00:41:39.668 16882-16882/com.sudocode.sudohide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.sudocode.sudohide, PID: 16882
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sudocode.sudohide/com.sudocode.sudohide.MainActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

**Comment by SudoCode755** [comment]
Hello,
Yes I am aware of this thnaks alot,
I found a fix for this, but I am taking my time in implementing a sustainable solution

**Comment by ghost** [comment]
:smile: Great thanks! Saw your update v1.28 in Xposed repository, which works well on my android 7.1.2. Can close now. 
BTW, I found if Lucky Patcher selected "Hide Lucky Patcher" option in its Xposed settings, SudoHide will crash when click Lucky Patcher. But, nvm, I will keep that option unselected because SudoHide can hide it better.
